CREATE TABLE `__TABLE_PREF__migrations` (
	`id`	INTEGER NOT NULL PRIMARY KEY UNIQUE,
	`run`	INTEGER default CURRENT_TIMESTAMP
);

CREATE TABLE `__TABLE_PREF__users` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`user`	TEXT NOT NULL UNIQUE,
	`pass`	TEXT NOT NULL,
	`admin`	integer NOT NULL DEFAULT 0,
	`first_name`	TEXT,
	`surname`	TEXT,
	`email`	TEXT
);

CREATE TABLE `__TABLE_PREF__authtokens` (
	`token`	TEXT NOT NULL,
	`user_id`	INTEGER NOT NULL,
	`created`	INTEGER NOT NULL
);